# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-01 17:09
from __future__ import unicode_literals

from django.db import migrations
import lucterios.framework.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_add_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='third',
            name='status',
            field=lucterios.framework.model_fields.FSMIntegerField(choices=[(0, 'Enable'), (1, 'Disable')], verbose_name='status'),
        ),
    ]
