# Generated by Django 4.2 on 2025-09-08 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payoff', '0012_supporting_internal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.9)], verbose_name='vat rate'),
        ),
    ]
